### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ali-master**

### CODE REVIEW

**Comment by pmbanugo** [comment]
I can't see any difference to what I have in the file you've edited

**Comment by ali-master** [comment]
replace **sring** with **string**

**Comment by pmbanugo** [comment]
thanks @ali-master

**Comment by ali-master** [comment]
Thank you too.

Have fun.

**Comment by pmbanugo** [comment]
You're welcome. I hope you're finding Hamoni Sync easy to use. Would be interesting to see what you're building with it

**Comment by ali-master** [comment]
Yes, of course.

I will use it as soon.

**Pull request merged**
